trigger:
- master
- develop
- refs/tags/*
- ci-test

variables:
  solution: 'Thinktecture.EntityFrameworkCore.sln'
  buildConfiguration: 'Release'

steps:

- script: |
    echo dotnet --version
    dotnet --version
  displayName: 'print infos'

- powershell: |
    . ./ci/ci.ps1
    Set-VersionSuffixOnTag "$Env:BUILD_SOURCESDIRECTORY" "$Env:BUILD_SOURCEBRANCH"
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  displayName: 'set version suffix'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    projects: $(solution)
    arguments: --configuration $(buildConfiguration)

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'NugetPackages'
